name: fluttergooglemapsapp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  google_maps_flutter: ^0.5.19
  font_awesome_flutter: ^8.2.0
  google_maps_webservice: ^0.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
